### Teste GET
#GET http://localhost:8000/api/v1/invoices
#Accept: application/json

### Cadastrar Invoice
POST http://localhost:8000/api/v1/invoices
Content-Type: application/json

{
    "user_id":4,
    "type":"P",
    "paid":1,
    "value":5600.00
}

### Atualizar Invoice
PUT http://localhost:8000/api/v1/invoices/18
Content-Type: application/json
Accept: application/json

{
  "user_id": 2,
  "type": "B",
  "paid": 1,
  "value": 150.75,
  "payment_date": "2025-06-10 21:00:00"
}

### Deletar Invoice
DELETE http://localhost:8000/api/v1/invoices/25
Accept: application/json
